# Generated by Django 5.2.6 on 2025-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='candidates/')),
                ('manifesto', models.TextField()),
                ('position', models.CharField(max_length=50)),
                ('ballot', models.CharField(max_length=50)),
                ('panel', models.CharField(max_length=50)),
            ],
        ),
    ]
