# Generated by Django 5.2.6 on 2025-09-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucsuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='election_type',
            field=models.CharField(choices=[('CUCSU', 'কেন্দ্রীয় ছাত্র সংসদ নির্বাচন'), ('HALL', 'হল সংসদ নির্বাচন')], default='CUCSU', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('vp', 'ভিপি'), ('gs', 'জিএস'), ('ags', 'এজিএস'), ('treasurer', 'কোষাধ্যক্ষ'), ('sports', 'খেলাধুলা ও ক্রীড়া সম্পাদক'), ('asst_sports', 'সহ খেলাধুলা ও ক্রীড়া সম্পাদক'), ('culture', 'সাহিত্য-সংস্কৃতি সম্পাদক'), ('asst_culture', 'সহ সাহিত্য-সংস্কৃতি সম্পাদক'), ('office', 'দপ্তর সম্পাদক'), ('asst_office', 'সহ-দপ্তর সম্পাদক'), ('welfare', 'ছাত্রী কল্যাণ সম্পাদক'), ('asst_welfare', 'সহ-ছাত্রী কল্যান সম্পাদক'), ('social_env', 'সমাজসেবা ও পরিবেশ বিষয়ক সম্পাদক'), ('law_hr', 'আইন ও মানবাধিকার বিষয়ক সম্পাদক'), ('freedom', 'মুক্তিযুদ্ধ ও গণতান্ত্রিক আন্দোলন বিষয়ক সম্পাদক'), ('career', 'ক্যারিয়ার ডেভেলপমেন্ট ও আন্তর্জাতিক বিষয়ক সম্পাদক'), ('communication', 'যোগাযোগ ও আবাসন সম্পাদক'), ('asst_communication', 'সহ-যোগাযোগ ও আবাসন সম্পাদক'), ('research', 'গবেষণা ও উদ্ভাবন সম্পাদক'), ('science_it', 'বিজ্ঞান ও তথ্যপ্রযুক্তি সম্পাদক'), ('health', 'স্বাস্থ্য সম্পাদক'), ('library_cafe', 'পাঠাগার ও ক্যাফেটেরিয়া বিষয়ক সম্পাদক'), ('executive', 'নির্বাহী সদস্য')], max_length=100),
        ),
    ]
