# Generated by Django 5.2.6 on 2025-09-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucsuapp', '0002_candidate_election_type_alter_candidate_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='ballot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election_type',
            field=models.CharField(choices=[('CUCSU', 'কেন্দ্রীয় ছাত্র সংসদ'), ('HALL', 'হল সংসদ')], default='CUCSU', max_length=20),
        ),
    ]
