# Generated by Django 5.2.6 on 2025-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucsuapp', '0004_candidate_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hall',
            field=models.CharField(choices=[('alaol', 'আলাওল হল'), ('af_rahman', 'এ. এফ. রহমান হল'), ('shahjalal', 'শাহজালাল হল'), ('suhrawardy', 'সুহরাওয়ার্দী হল'), ('shah_amanat', 'শাহ আমানত হল'), ('shaheed_abdur_rab', 'শহীদ আবদুর রব হল'), ('pritilata', 'প্রিতিলতা হল'), ('masterda_surja_sen', 'মাস্টারদা সূর্য সেন হল'), ('shaheed_farhad_hossain', 'শহীদ ফরহাদ হোসেন হল'), ('bijoy_24', 'বিজয় ২৪ হল'), ('nawab_faizunnesa', 'নওয়াব ফয়জুন্নেসা হল'), ('atish_dipangkar_srigyan', 'অতীশ দীপঙ্কর শ্রীজ্ঞান হল'), ('artist_rashid_chowdhury', 'শিল্পী রশীদ চৌধুরী হল'), ('deshnetri_begum_khaleda_zia', 'দেশনেত্রী বেগম খালেদা জিয়া হল'), ('shamsun_nahar', 'শামসুন নাহার হল')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
