# Generated by Django 5.2.6 on 2025-09-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucsuapp', '0005_candidate_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='hall',
            field=models.CharField(choices=[('alaol', 'আলাওল হল'), ('af_rahman', 'এ. এফ. রহমান হল'), ('shahjalal', 'শাহজালাল হল'), ('suhrawardy', 'সোহরাওয়ার্দী হল'), ('shah_amanat', 'শাহ আমানত হল'), ('rab_hall', 'শহীদ আবদুর রব হল'), ('pritilata', 'প্রীতিলতা হল'), ('surja_sen', 'মাস্টারদা সূর্যসেন হল'), ('shaheed_farhad', 'শহীদ ফরহাদ হোসেন হল'), ('bijoy_24', 'বিজয় ২৪ হল'), ('nawab_faizunnesa', 'নওয়াব ফয়জুন্নেসা হল'), ('atish_dipangkar', 'অতীশ দীপঙ্কর শ্রীজ্ঞান হল'), ('artist_rashid_chowdhury', 'শিল্পী রশীদ চৌধুরী হোস্টেল'), ('khaleda_hall', 'দেশনেত্রী বেগম খালেদা জিয়া হল'), ('shamsun_nahar', 'শামসুন নাহার হল')], max_length=50),
        ),
        migrations.CreateModel(
            name='VoteIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cucsuapp.candidate')),
            ],
            options={
                'unique_together': {('candidate', 'ip_address')},
            },
        ),
    ]
